# Generated by Django 3.1 on 2020-12-24 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userlogtitle', models.CharField(max_length=40, unique_for_date='datecreated')),
                ('userdiary', models.TextField()),
                ('userpictures', models.FileField(blank=True, upload_to='')),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ManyToManyField(blank=True, to='mymodels.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('bio', models.TextField(blank=True, default='no bio', max_length=300)),
                ('userdp', models.FileField(blank=True, default='C:\\Users\\Anthony\\Pictures\\jeremy-perkins-UgNjyPkphtU-unsplash.jpg', upload_to='')),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('friends', models.ManyToManyField(related_name='_userdetail_friends_+', to='mymodels.UserDetail')),
                ('usermodel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userpost', models.ManyToManyField(to='mymodels.UserPost')),
            ],
        ),
    ]
