# Generated by Django 3.1 on 2020-12-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymodels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='last_name',
            field=models.CharField(default='freyo', max_length=200),
            preserve_default=False,
        ),
    ]
