# Generated by Django 3.1 on 2020-12-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymodels', '0002_auto_20201226_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='dob',
            field=models.DateField(blank=True),
        ),
    ]
