# Generated by Django 3.1 on 2020-12-27 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mymodels', '0003_auto_20201226_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='password',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_userdetail_friends_+', to='mymodels.UserDetail'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='usermodel',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='userpost',
            field=models.ManyToManyField(blank=True, to='mymodels.UserPost'),
        ),
    ]
