# Generated by Django 3.1 on 2020-12-27 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymodels', '0004_auto_20201227_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='dob',
        ),
    ]
