# Generated by Django 3.1 on 2020-12-27 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mymodels', '0005_remove_userdetail_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='usermodel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
